---
language: python
services: docker

env:
  global:
    - ROLE_NAME: knora-stack
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME dhlab-basel.$ROLE_NAME
  - cd dhlab-basel.$ROLE_NAME

script:
  # Run tests.
  - molecule test
